--- #chrony-jinja.yml

- hosts: all 

  vars:

    chrony:
      Debian:
        package_name: chrony
        service_name: chronyd.service
        conf_path: /etc/chrony/chrony.conf
        
      Ubuntu:
        package_name: chrony
        service_name: chronyd.service
        conf_path: /etc/chrony/chrony.conf
      Rocky:
        package_name: chrony
        service_name: chronyd.service
        conf_path: /etc/chrony.conf
      openSUSE Leap:
        package_name: chrony
        service_name: chronyd.service
        conf_path: /etc/chrony.conf

  tasks:

    - name: Update package information on Debian/Ubuntu
      apt:
        update_cache: true
        cache_valid_time: 3600
      when: ansible_os_family == "Debian"

    - name: Install Chrony
      package:
        name: "{{ chrony[ansible_distribution].package_name }}"

    - name: Start & enable Chrony
      service:
        name: "{{ chrony[ansible_distribution].service_name }}"
        state: started
        enabled: true
        
    - name: Set chrony configuration
      template:
        dest: "{{ chrony[ansible_distribution].conf_path }}"
        mode: 0644
        src: templates/chrony.conf.j2        
      notify: Restart Chrony

  handlers:

    - name: Restart Chrony
      service:
        name: "{{ chrony[ansible_distribution].service_name }}"
        state: restarted