---  # chrony.yml

- hosts: redhat

  tasks:

    - name: Install Chrony
      dnf:
        name: chronyd

    - name: Start & enable Chrony
      service:
        name: chronyd
        state: started
        enabled: true

    - name: Set chrony configuration
      copy:
        dest: /etc/chrony.conf
        mode: 0644
        content: |
          # /etc/chrony.conf
          server 0.fr.pool.ntp.org iburst
          server 1.fr.pool.ntp.org iburst
          server 2.fr.pool.ntp.org iburst
          server 3.fr.pool.ntp.org iburst
          driftfile /var/lib/chrony/drift
          makestep 1.0 3
          rtcsync
          logdir /var/log/chrony
      notify: Restart Chrony

  handlers:

    - name: Restart Chrony
      service:
        name: chronyd
        state: restarted